version: 2.1

orbs:
  eb: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    description: "Setup Spring boot application and run tests"
    docker:
      - image: cimg/openjdk:21.0.2
    steps:
      - checkout
      - run:
          name: Build
          command: cd academiverse-api && mvn -B -DskipTests clean package

  deploy:
    docker:
      - image: "cimg/aws:2024.03"
    description: "Deploying updates to Elastic Beanstalk"
    steps:
      - eb/setup
      - run:
          name: Set up Elastic Beanstalk
          command: |
            cd academiverse-api
            eb init academiVerseApi -r $AWS_DEFAULT_REGION -p corretto-17
            echo "deploy:
                  artifact: target/academiverse-api-0.0.1-SNAPSHOT.jar" >> .elasticbeanstalk/config.yml
      - run:
          name: Deploy to Elastic Beanstalk
          command: |
            cd academiverse-api
            eb deploy spring-environment

workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          context: aws-credentials

